project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/joydon-710

format:
  html:
    theme: cosmo
    css: styles.css